from django.contrib import admin
from .models import *
from apps.perfilesmedicos.models import *
# Register your models here.
admin.site.register(SintomasGenerales)
admin.site.register(EstadosAnimo)
admin.site.register(SintomasAlteracionGlicemica)
admin.site.register(ContextoMedicion)
admin.site.register(TipoConcentracion)
admin.site.register(TipoDosis)
admin.site.register(ModoAdministracion)
admin.site.register(Marca)
admin.site.register(EstadoEnfermedad)
admin.site.register(TipoComida)
admin.site.register(Latido)
admin.site.register(TipoSangre)
admin.site.register(PerfilBasico)
admin.site.register(ContactosBasico)
admin.site.register(SintomasGeneralesPaciente)
admin.site.register(SintomasAlteracionGlicemicaPaciente)
admin.site.register(EstadosAnimoPaciente)
admin.site.register(Peso)
admin.site.register(Talla)
admin.site.register(Glucemia)
admin.site.register(Hemoglobina)
admin.site.register(Colesterol)
admin.site.register(Presion)
admin.site.register(RutinaEjercicio)
admin.site.register(RutinaAlimentacion)
admin.site.register(Medicamento)
admin.site.register(Terapia)
admin.site.register(ResultadosLab)
admin.site.register(Cita)
admin.site.register(ResumenClinico)
admin.site.register(Enfermedad)
admin.site.register(Cirugia)

admin.site.register(Perfiles)
admin.site.register(Contactos)
admin.site.register(RedesSociales)
admin.site.register(PerfilProfesional)
admin.site.register(PerfilAcademico)
admin.site.register(PreguntasRespuestas)
admin.site.register(Pais)
admin.site.register(Dpto)
admin.site.register(Ciudad)
admin.site.register(Especialidad)
admin.site.register(Servicios)
